global:
  timezone: Asia/Tokyo
  cache:
    base: /tmp
  log:
    level: info

plugins:
  - module: SubscriptionFeed
    config:
      feeds:
        - http://reretlet.tumblr.com/rss

  - module: StorePermalink
    config:
      db: tumblr.db

  - module: FilterImage

  - module: FilterTumblrResize

  - module: StoreTargetLink
    config:
      path: /tmp
      interval: 2

