global:
  timezone: Asia/Tokyo
  cache:
    base: /tmp
  log:
    level: info

plugins:
  - module: SubscriptionURI
    config:
      urls:
        - http://id774.net/

  - module: ExtractLink

  - module: PublishDump
